# Generated by Django 5.0.1 on 2024-01-23 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_customer',
            field=models.BooleanField(default=False),
        ),
    ]
