# Generated by Django 5.0.1 on 2024-01-26 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_account_groups_account_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='account',
            name='user_permissions',
        ),
    ]
